### ISSUE TITLE
The long help for >>perms is incorrect

### ISSUE THREAD

**Issue by Mee42** [oaktoncsclub/project-bot#10]
It appears to be the same as the long help for `help`. This is an easy fix

**Comment by americanpotato** [comment]
I added a pull request that changes the long help for perms to: "call this command to learn what your permission level is". Here is a link to it: [https://github.com/oaktoncsclub/project-bot/pull/12/commits/08dfbd65eb65b7f55e8c5fef8cac47f0b02e6478](url)

**Comment by Mee42** [comment]
Merged!
