### ISSUE TITLE
The class name `TestCommands` is vague

### ISSUE THREAD

**Issue by Mee42** [oaktoncsclub/project-bot#3]
Could there be a better name for it?

Is there any other poorly-named classes or methods in this project that could be refactored and renamed to something better?

**Comment by Keerthi4308** [comment]
Hey looking into this

**Comment by Keerthi4308** [comment]
As far as I understood the TestingCommands file intends to test commands that project-bot users will use, am I right?

**Comment by Mee42** [comment]
I can initially created the class to test the command api, and I wrote some basic commands like ping and perms.

I think that you could interpret it as commands used to test the bot? I'm not sure. 

We could definitely have a GeneralCommands class that holds more general commands, though I'm not sure how general these commands are

For example, the `contibute` command is in this file, and it isn't a command for testing. But the `ping` command is probably not going to used by people outside of testing the bot.

Maybe we need to make another class (each class is a command group?) to organize commands better? What do you think?

**Comment by Keerthi4308** [comment]
Yes I agree with you, having a separate class for command group would be more easy to understand and brings modularity in the codebase say BotCommandsTest, UserCommandsTest. But since we have just few commands we are testing, we can a generic name for now.

**Comment by Mee42** [comment]
Thats a good point - we aren't at the point where having too many commands in one place/the wrong place is a problem.

Thanks for your input, though.

I'll close this issue.
